### ISSUE TITLE
Max object should autoconnect to an available crow

### ISSUE THREAD

**Issue by trentgill** [monome/crow-max-and-m4l#22]
cc @dndrks @whimsical-sam. this issue is moved here from the main crow issue tracker.

Query the 'correct' looking ports.
Determine what the port should look like (compare mac vs win).
Possible to attempt re-connect after dropped connection?
Possible to warn user that no device was found / dropped?

**Comment by dndrks** [comment]
I actually feel like this is nearly done -- Max object totally auto-connects on Mac and Windows now, but it hasn't been migrated into the m4l devices. Will add to testing, thanks Trent!

**Comment by dndrks** [comment]
good to ship with the new crow firmware!
