### ISSUE TITLE
w_synth m4l graphic interface problem

### ISSUE THREAD

**Issue by zunaito** [monome/crow-max-and-m4l#24]
hi @dndrks 

sorry if this could be handled more easily somewhere else...might be a simple fix but my w_synth m4l device looks like this:

[screenshot of my device](https://user-images.githubusercontent.com/23157696/72555135-0a606600-386a-11ea-83bc-d61826f42b59.png)

i haven't experienced sonic or control errors, just a slightly wonky UI

**Comment by dndrks** [comment]
this is great!

ah, you're on Live 9?

**Comment by zunaito** [comment]
yes

and max 7

**Comment by dndrks** [comment]
that'd do it -- the UI element is different across the versions. thanks for the heads up!!

**Comment by dndrks** [comment]
updated, please check new device and lmk?

**Comment by zunaito** [comment]
sorry if i'm being dense...i can't find the updated device

if it hasn't been added to the main page yet, where can it be found?

**Comment by dndrks** [comment]
all good! should be here: https://github.com/monome/crow-max-and-m4l/tree/object-update

**Comment by dndrks** [comment]
closing this as w_synth will receive some changes <3
