### ISSUE TITLE
modulating ^^outs remote with audio-based devices (Live's LFO) leads to unresponsive crow

### ISSUE THREAD

**Issue by jlmitch5** [monome/crow-max-and-m4l#25]
![Screen Shot 2020-01-16 at 9 23 52 PM](https://user-images.githubusercontent.com/1342624/72579233-84aedb80-38a6-11ea-8711-d7852597b222.png)

I have a chain of m4l lfos, modulating the remote ^^out v knobs of 3 outputs on crow.  periodically crow will stop responding, and I have to unplug and plug back in the usb from crow, refresh the ^^command_center and choose crow again (which immediately causes the crow to start responding again).

Sometimes crow seems to stop responding without any manual changes, sometimes it seems to happen directly after I tweak a parameter on one of the outs (like bias) or once when I tried to create another midi track.

I'm on macOS 10.14.5, live 10.1.7, crow 1.0.2 and the latest master of this repo.

I'm not sure how I could give you log info, but if that would be helpful and you can tell me how to access it I can paste it here!

**Comment by dndrks** [comment]
hey @jlmitch5 , thanks so much for the report! please try again on the 1.0.3 updates and lmk if this remains an issue!

**Comment by jlmitch5** [comment]
hey @dndrks, just got a chance to upgrade crow (and also grabbed latest master of this repo), but unfortunately the same issue.  It's like it will work and then eventually just stop responding to messages.

I'm not sure this will just magically drop in to ableton for you, but here's the rack I just tried


[crow out bug rack.adg.zip](https://github.com/monome/crow-max-and-m4l/files/4095252/crow.out.bug.rack.adg.zip)

**Comment by jlmitch5** [comment]
![Screen Shot 2020-01-21 at 11 31 57 PM](https://user-images.githubusercontent.com/1342624/72865544-464e5d80-3ca6-11ea-8382-43a8c11b17f0.png)
![Screen Shot 2020-01-21 at 11 32 07 PM](https://user-images.githubusercontent.com/1342624/72865545-464e5d80-3ca6-11ea-8efd-b8d025483da6.png)

**Comment by dndrks** [comment]
thanks john!

- does this only happen with multiple instances?
- does this only happen with the `remote` tool?
- are you essentially trying to get chaotic lfos through each of the crow outs?

**Comment by jlmitch5** [comment]
Busy few days, sorry @dndrks.  I’ll get to more debugging this weekend.  Is their some place I could go to get you helpful log output, happy to do so, just not sure where it would be.

I have not tried super fast chaotic lfo with just a single instance.  I did have the same issue with a midi note thing (can’t remember the exact one) and a couple of these remotes.

I’m not really specifically looking to make crow a quad random lfo, more just trying to figure out a creatively-inspiring ableton + modular workflow.  What I was specifically trying to do is remote control of a mangrove (outs on crow go to pitch, air, barrel, formant) so that I could do some in the box stuff but with a fun analog voice.

I do love the ableton lfos w the noise and smoothing tho!

**Comment by dndrks** [comment]
hey @jlmitch5 -- no worries at all! it's not your responsibility :)

i was able to replicate (one ^^outs instance, on `remote`, using ableton's LFO).

also found a scripting bug, but fixing that didn't change crashing when the LFO device was modulating. oddly, hand-modulating in the same manner didn't result in any errors, so there's got to be something with the modulation source. i'll continue to dig, thank you so so much!

**Comment by dndrks** [comment]
@jlmitch5 , lol, this is insane but I'm able to modulate the heck out of `remote` with [Survey](https://llllllll.co/t/survey-m4l/28719/17). Live's built-in LFO is actually an audio signal, which is sorta mushed into a data container, but Survey is 100% data.

I wonder if the architecture difference has any bearing here. But I was able to fully modulate `remote` **without** crashing with this fixed version of `^^outs` and a data-based modulator.

[^^outs-fixed.amxd.zip](https://github.com/monome/crow-max-and-m4l/files/4111390/outs-fixed.amxd.zip)

**Comment by dndrks** [comment]
ok, testing more -- i had "put hard disk to sleep" when possible checked on my energy saver prefs, disabled that now. let's see how long we can get -- going strong for 10 mins rn.

**Comment by dndrks** [comment]
WILD. after turning off "put hard disk to sleep when possible":

- had the device running in the bundled Max edit window for an hour w/Survey, receiving consistent modulation for an hour. no crashes.
- had the device running in Live for another hour w/Survey, no crashes. i think the energy saver pref might've been it afaik...

**Comment by dndrks** [comment]
> I wonder if something might be getting throttled every so often, which sends crow bad data?

just spitballin', but this actually makes a lot of sense -- Live naturally prioritizes audio over data. so it makes sense for the built-in Live LFO to be a device rooted in _audio_, because it won't suffer the same dropouts that data can when the data is bottlenecked or de-prioritized for audio events. but when crow is being modulated by a device which has a natively higher priority, then crow won't receive the packets with parity. I assume that the data signals being generated by Live's LFO will be codified in Live's scheduler as audio, so it won't be mussed with.

dang...this feels right, but i'll continue to test.

in the meantime, @jlmitch5 if you read nothing else from this insane diatribe:
- please download the "fixed" version of outs posted above
- in your Mac's Energy Saver preferences, ensure "put hard disks to sleep when possible" and "enable power nap" are both unchecked for battery _and_ power adapter
- try using the _excellent_ Survey to data-modulate

**Comment by jlmitch5** [comment]
Awesome thanks for the troubleshooting and your explanation @dndrks!

Now that you mention, I was actually seeing the unresponsiveness arise during seemingly unrelated things.  Such as when I tried to add another track in live or something.  Maybe those sorts of things were "interrupts" to the scheduling queue, and that caused things to happen out of order, confusing crow?

Gonna try things out now based on your ideas.  Will report back

**Comment by jlmitch5** [comment]
Yep everything works great!  I sent you a video showing what I was doing on instagram.  Thanks again for your help.  I'm good to close this if your cool with that.

**Comment by dndrks** [comment]
thanks @jlmitch5 !! <3333
