### ISSUE TITLE
certain combinations of ii.jf.play_voice arguments crash crow

### ISSUE THREAD

**Issue by dndrks** [monome/crow-max-and-m4l#32]
it seems that a combination of quickly sending negative values to `pitch` and two decimal point precision values to `level` reliably crashes crow hardware. JF remains responsive, however, both to i2c messages from other devices on the bus and to panel controls.

this _only_ happens in Max + Max for Live -- i cannot reproduce the issue in druid using the same circumstances.

to repro in Max:

- load the patcher below
- by default, `pitch` values are all positive -- you can change this with the radio buttons at the bottom of the patcher
- using the radio buttons toward the top of the patcher, you can change whether JF's `level` argument is receiving an integer, a float with one-decimal precision, or a float with two-decimal precision
- when pitches are all positive, `level` float precision doesn't matter
- when pitches include negative values, crow remains stable for integer + one-decimal precision values to `float` -- things quickly crash if two decimal `level` precision is used when negative `pitch` values are cycling, however!!

<details>
<summary> patcher </summary>
<pre><code>
----------begin_max5_patcher----------
1933.3ocyas0ihhDE9Y6eEULYSlIiiotRAa1W1eGSuoCMVZWcTvAvt6YmL6u
8EpCn3EfR.Y7gVygFkuuSctVmxe9vjoOG8gJYJ5OQeCMYxOeXxDykxuvjB4I
S23+QvZ+DysMciJIwekZ5L3+kp9H0bc7bon7haiUIpvT+TcT3Sq0gpfncgla
iVbGg61DsKcsJ07kRJtpdg4qJ54W+pfT9kA2W5O1p.XNcJ5eJeN9oAunCW8T
rJHE9ubJdtXFR3fmimgXz7WoYut+yj8j0gkOXZ9090COj+xLKU.AQa1jQtyT
.aiRzo52Tn27WuSk7XXTnBEpV4e3hkelKpRtVkF9BJM7z50LfFQhk4uQHLi9
gUmlgzAMSn58LTblhYcj+hbqFzdz05pOW1wUeCqbjt.Uadwe.o3WPD64lSsb
Smud2J8jBhgXd4F5Cqscr+Bczp3ncasmNG758i82nRUwOoB8edsppQZWVFKM
UMKlLdsKikXJUso7AT9XSz+qppGD3EV4FVnSxg5B34l8bxdHCmYQx65Ltgn1
qL4cytmRLpJIgm+lnkndrALp2e8eH+kYq4nfnvrPVopEnzHTPbz6nufdcIRm
fzgnjeDl9BZSzB0LTRpebJJQ88cpvflCI1Z.ONqo.dFcBOKRWleBwSLZA7hQ
gQoJ6Wz6XpNJ3lHLzj407ZNd.spafdWZMpojRkFtPHMNY3iXWW8J1Gvl10jQ
YogxKEwkeqBWWG295UPNm9Um03Strmq8rSzM1wbn+tXm8bqi4JXX9Mla0EVL
CmJDAQQLD+xzTbNMIM38M6j+ZzfECoFM4FkNMGnQLbr1jTKK+HoNNyu.matD
wJTtsJFYlTDbWntXugm0oQqVs19bcdcpXQKYIToHkW95MOQeFAhiPDr8Ns0m
p+Y+vU1PRArTxFuFa0OFRdLjdwJ0X1VE.AKq9E+5tjT8Rcfoa2p5pKPbBEVW
gLNvhLWNjKu0w77N3WnBza7WiVqdSs1T85yqsu3GB1oopeDlhRoLSrIh.ZXE
OBVtIaiybpVlUXdNAPONUqm+5x4aW6+imdKRGn9Da1eLmtLKT4b5mebp8N36
WlWFElV1+EIuvtVSVk+IByhJX9x96Xs+5FzcRA3m6HLIvHPDcxcgti1McWk.
I2XkmfPtaUdjtp7Dijxqzq8Fp7pMTbVoDqxJlnaAi3dMxJYNcbcuiCEcM1CR
5XEHhaJojPMsLPgMs5dKPzUo4FKGItm2cqlizEMmGarBAAa8yuAMWW1Le2t0
nJA1MShq3Nd27Y7Nua9DFTWKzb1cx14yXC+14WrPRIdG1OeAtO6mO6z8ymV6
94ea1Rel8JTZGs9gpLXTq1Re9.tETPrv7Mq+SjOaeViNtI1tycc4NXJg5wEd
LWRtgBybQBggcERtiTlOaiwqi2z2iNsuufX+jWTIH8RzViEfNY+vc62LLHXZ
SQ5cbf4VXdi.ZgQYJFWSKhtWUZRWwnUZFLajLcnI1J8trGwqT44NV8Hh42sJ
ORGUddjQq.M2eSJu7QudY8A6BFSMt25lsjblk4obLTjeEUoYtCSPySN.RlmR
90Ol8IQ6hCJwW4f4PGdPKTIo5v86n32NLRcDY+MsQuXaTl0UwijC865.chTT
VsQZ+mHJdgJt9EIqAKu2fkA0QMFfUzevJoiDXyOpX80L.1AVAzpAGSOW5hDo
W3NexVHZK39DxcBtgC5j.bAKIQtzfaPXsqF0RWMgoemZLHv8CrN8Grft7hfc
j7rnV5YcKUj79C1iiYcCAK2JvhaxchRMoqkEMlWQpmq5bqbeDMgMgYqdjEgl
NHzWjYsuRaHSBM4CUMdhD9HEJd.TnV4F4XAr47JJTNu2HyyBf0XLctAJb.WU
D5a1FavkiE.SJq.Lor+Kk1fL2F8MnvxGozLClgwQRLJANnYFSP1QkhOP4Hsi
HtCCQDvwZrFhvu8DwizWhTbLlg4NYjNmHxQfHxdRjhI.JcX6mG3fmayJuWLd
XXh.NoE0vD1Xvj95tScJFvs4rtYjNmIN2dljOExVIhKo7LvVHbNToi.TEVCU
A1sdnJFAWVl0Pshv4P0s+8uwZApzFit3QmSEGZfCKp1NWgD2ANBet6kFi9No
NVz2ILStRfdhjW0dRk2fB9M7fzFOZzpNKjsTrG5EMVYjFBcbalwzFKqlaZUp
DZE+xNFBnYSE+DY6UBJfeCYE3jv5eoy1nzxmmV8saVjDlgKF0nydo9hMlsXi
zRbohjrE+fTNVpD2Rwfgahs3lUOtgJz7vUlh6IRvPcIdvcR5eCdmTmbWvcYI
x.R4t3J3tTZ3wsn23trGkhsLoTe6cS02RQusuKpJXbsuOo.qtf6hBuFYbaSu
hMECl4Nmc5fyYvuELBT0qQpuMmakaXikiQnE8EAGx4JR8DaLtsK80iM9AGnC
5sAvchYU5BtM5MnPpBjRk82ziQ6qsWohhejZi2e01oM90kR.J54a3KA3z9q6
B3JZstMvAiF0e612TwIEe+FbMci+qQPuKyLh5PPz7KmZZr5Mc48aN.JS8iCd
QmpBR2ECSt9CG3DqMM+.9DGtSWrwWYZjrGoY7x4S4NYqOPdyTne3WO7+.H14
.kA
-----------end_max5_patcher-----------
</code></pre>
</details>

this one was difficult to nail down, but i'm feeling confident that it's the source of the crashes folks have reported with the JF M4L devices! i wonder if there's some high weirdness happening in the **[crow]** string parser subpatch? unsure, but happy to help test any potential solutions! also, lmk if anything needs further detail @trentgill !

**Comment by trentgill** [comment]
thanks for the work on this @dndrks !

my guess is it's not anything to do with the actual messages that are being sent, but something more general about either string length (there was a previous issue when sending multiples of 64 characters at a time), or simply a bandwidth issue where a buffer is overrunning on crow (though there is at least minimal protection against this kind of thing).

i'll take a look at the patch but i don't have my crow setup handy for another week or so to do on device testing.

---

also weirdly, i just ran the patcher you posted and Max straight up crashed after a few minutes of the metro running (without crow attached). i wonder if there's something *else* weird going on?

**Comment by dndrks** [comment]
rad, tyty!

>also weirdly, i just ran the patcher you posted and Max straight up crashed after a few minutes of the metro running (without crow attached). i wonder if there's something else weird going on?

i wonder if hammering whatever other serial port instantiates when crow's not connected (eg. `Bluetooth-Incoming-Port`) is the trouble?

**Comment by dndrks** [comment]
seems to have been addressed in #33 with @trentgill 's deep-dive!
